100 application viewing and styling
MasterCoookie/szychta-pl pull request #112
Opened 2023-05-09 22:12 UTC by tomazaw

2023-05-09 22:14 UTC, macibol775 commented on controllers/applyController.js
> +    relativeDocuments = relativeDocuments.split(',');
tab

2023-05-09 22:16 UTC, macibol775 commented on views/applications/show_applicant_applications.ejs
> +            <div><%= jobOffersWithId[application.jobOffer_id].title %></div>
tabulation

2023-05-09 22:18 UTC, macibol775 commented on views/applications/show_applications.ejs
łer miejsce do wyświetlenia aktualnego statusu

2023-05-09 22:18 UTC, tomazaw commented on views/applications/show_applications.ejs
Jak to zaimplementujesz to to dodam, to jest jedna linijka

2023-05-09 22:20 UTC, macibol775 commented on controllers/applicationController.js
> +        const applicantsWithId = await getApplicantNames();
trzeba to było (przy 1 użyciu) wywalać do osobnej funkcji?

2023-05-09 22:21 UTC, tomazaw commented on controllers/applicationController.js
> +        const applicantsWithId = await getApplicantNames();
Chciałem użyć do tego reduce, ale problem jest taki że reduce nie może być asynchroniczny, dlatego rozwiązałem to w ten sposób

2023-05-09 22:22 UTC, macibol775 commented on controllers/applicationController.js
> +        res.render('applications/show_application_details', { title: 'Pokaż aplikację', application, jobOffer, applicant, skillNames, user: req.session.applicant ?? req.session.employer, scrollable:
Nazwa karty w przeglądarce "Pokaż aplikację" trochę bez sensu, lepiej: wyświetlanie aplikacji, zarządzanie aplikacją, przeglądanie szczegółów aplikacju

2023-05-09 22:23 UTC, macibol775 commented on controllers/applicationController.js
> +const show_applicant_applications = async (req, res) => {
typ zapytania do nazwy

2023-05-09 22:23 UTC, macibol775 commented on controllers/applicationController.js
> +        const jobOffersWithId = await getJobOffers();
j.w.

2023-05-09 22:24 UTC, macibol775 commented on controllers/applicationController.js
> +        res.render('applications/show_applicant_applications', { title: 'Wyświetl swoje aplikacje', applications, jobOffersWithId, user: req.session.applicant, scrollable: true});
Tytuł - j.w. (to nie nazwa przycisku, tylko karty/okienka)

2023-05-09 22:25 UTC, macibol775 requested changes
Some minor changes, mainly displayed names and type of request in controller

2023-05-09 22:26 UTC, macibol775 commented on views/applications/show_applications.ejs
wystarczy pusty div

2023-05-09 22:28 UTC, macibol775 approved these changes

2023-05-09 22:29 UTC, macibol775 commented
Gratuluję numeru 100

2023-05-10 07:25 UTC, MasterCoookie approved these changes
Pozmieniaj te mniejsze pierdoły w wolnym czasie

2023-05-10 07:25 UTC, MasterCoookie commented on controllers/applicationController.js
> +        res.render('applications/show_applicant_applications', { title: 'Wyświetlanie swoich aplikacji', applications, jobOffersWithId, user: req.session.applicant, scrollable: true});
Tytuł za długi "wyświetl aplikacje wystarczy"

2023-05-10 07:25 UTC, MasterCoookie commented on controllers/applyController.js
> +    console.log(relativeDocuments);
remove debug logs

2023-05-10 07:25 UTC, MasterCoookie commented on public/js/apply.js
> +    console.log(filesArray);
remove debug logs

2023-05-10 07:27 UTC, merged