106 create admin routes
MasterCoookie/szychta-pl pull request #117
Opened 2023-05-10 20:33 UTC by WojciechPtas

DO NOT REVIEW

2023-05-10 20:35 UTC, WojciechPtas commented on controllers/adminController.js
> +        console.log("New employer %s %s with permission level %s created", name, surname , permissionLevel);
space before comma

2023-05-10 20:44 UTC, WojciechPtas commented
Middleware is to be implemented

2023-05-10 20:51 UTC, macibol775 commented on controllers/adminController.js
> +                var length = 8,
var?

2023-05-10 20:51 UTC, macibol775 commented on controllers/adminController.js
> +                var length = 8,
const

2023-05-10 20:51 UTC, macibol775 commented on controllers/adminController.js
> +                charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+?><:{}[]";
const

2023-05-10 20:51 UTC, macibol775 commented on controllers/adminController.js
> +                var retVal = "";
let

2023-05-10 20:52 UTC, macibol775 commented on controllers/adminController.js
> +        const org = await Organisation.create({ name, description });
not used

2023-05-10 20:53 UTC, macibol775 commented on controllers/adminController.js
> +        const employer = await Employer.create({ email, password, name, surname,permissionLevel,organisation_id });
not used

2023-05-10 20:54 UTC, macibol775 commented on controllers/adminController.js
> +        await Employer.findByIdAndUpdate(employer_id, {name, surname, email, permissionLevel,organisation_id});
Czy organisation_id może być modyfikowane?

2023-05-10 20:54 UTC, macibol775 commented on controllers/adminController.js
> +        await Employer.findByIdAndUpdate(employer_id, {name, surname, email, permissionLevel,organisation_id});
brak spacji po przecinku

2023-05-10 20:56 UTC, macibol775 commented on models/employerModel.js
> +        type: mongoose.Schema.Types.ObjectId,
"mongoose." not needed, copilot detected

2023-05-10 20:58 UTC, macibol775 commented on public/js/modifyEmployer.js
> +            console.log(request.response);
have you found any practical usage of this log?

2023-05-10 20:59 UTC, macibol775 commented on controllers/adminController.js
> +const delete_organisation_post = async (req, res) => {
deleteOrganisation_post

2023-05-10 21:01 UTC, MasterCoookie requested changes
Change vars and protect apropriate routes

2023-05-10 21:01 UTC, MasterCoookie commented on views/organisation/manage_organisation.ejs
> +    <% var organisation_id = locals.organisation ? organisation._id : null;%>
dont use var

2023-05-10 21:02 UTC, macibol775 commented on views/employer/manage_employer.ejs
> +                    <label class="control-label col-sm-8 pt-2 pb-1 m-0" for="surname">Email:</label>
for=dupa

2023-05-10 21:02 UTC, macibol775 commented on views/employer/manage_employer.ejs
> +                        <input type="text" id="email" name="email" rows="8" cols="64" class="form-control shadow bg-white rounded" value="<% if(locals.employer && employer.email != null) {%><%= emplo
type=email

2023-05-10 21:05 UTC, macibol775 commented on views/employer/manage_employer.ejs
> +                        <select type="text" id="permissionLevel" name="permissionLevel" rows="8" cols="64" class="form-control shadow bg-white rounded" value="<% if(locals.employer && employer.permis
select does not have type attribute (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attributes)

2023-05-10 21:05 UTC, macibol775 commented on views/employer/manage_employer.ejs
> +                        <select type="text" id="organisation_id" name="organisation_id" rows="8" cols="64" class="form-control shadow bg-white rounded" value="<% if(locals.organisation && organisatio
jak niżej

2023-05-10 21:05 UTC, macibol775 commented on views/employer/manage_employer.ejs
> +                        <select type="text" id="organisation_id" name="organisation_id" rows="8" cols="64" class="form-control shadow bg-white rounded" value="<% if(locals.organisation && organisatio
rows, cols?

2023-05-10 21:05 UTC, macibol775 commented on views/employer/manage_employer.ejs
> +                        <select type="text" id="permissionLevel" name="permissionLevel" rows="8" cols="64" class="form-control shadow bg-white rounded" value="<% if(locals.employer && employer.permis
rows, cols?

2023-05-10 21:06 UTC, macibol775 commented on views/employer/manage_employer.ejs
> +                        <input type="text" id="surname" name="password" rows="8" cols="64" class="form-control shadow bg-white rounded" value="<%=passwordGenerator()%>" required="" class="form-contro
id="surname" name="password"
rows cols???!!!???

2023-05-10 21:06 UTC, macibol775 commented on views/employer/manage_employer.ejs
> +                        <input type="text" id="surname" name="surname" rows="8" cols="64" class="form-control shadow bg-white rounded" value="<% if(locals.employer && employer.surname != null) {%><%=
rows cols??

2023-05-10 21:07 UTC, macibol775 commented on views/organisation/manage_organisation.ejs
> +            <form class="form-horizontal" id="offerForm">
not offer form

2023-05-10 21:09 UTC, macibol775 requested changes
Terrible html, ugly things in js, don't rely so much on copilot or copy-paste

2023-05-10 21:49 UTC, macibol775 commented on controllers/adminController.js
> +                const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+?><:{}[]";
= and - not allowed?

2023-05-10 21:58 UTC, macibol775 commented on views/employer/manage_employer.ejs
> +                    <label class="control-label col-sm-8 pt-2 pb-1 m-0" for="surname">Email:</label>
don't resolve unresolved issues!!!

2023-05-10 21:59 UTC, macibol775 commented on controllers/adminController.js
> +        Organisation.create({ name, description });
BUG await

2023-05-10 22:00 UTC, MasterCoookie commented on controllers/adminController.js
> +        Organisation.create({ name, description });
Yeah, this will not throw an error, but will also not work

2023-05-10 22:00 UTC, macibol775 commented on models/employerModel.js
> +        required: false
why?

2023-05-10 22:01 UTC, MasterCoookie commented on models/employerModel.js
> +        required: false
I requested it, tho, for future code, no need to specify not required

2023-05-11 08:48 UTC, tomazaw requested changes

2023-05-11 08:48 UTC, tomazaw commented on controllers/adminController.js
> +            Object.values(e.errors).forEach(({ properties }) => {
syntax, if using one element in foreach ({}) is not needed

2023-05-11 08:48 UTC, tomazaw commented on controllers/adminController.js
> +        const all_organisations = (await Organisation.find({})).map(org => org.toObject());
i think that brackets inside find are not needed

2023-05-11 08:48 UTC, tomazaw commented on public/js/modifyEmployer.js
> +export { initializeModifyEmployerSubmitListener as initializeModifyEmployerSubmitListener };
export as the same thing

2023-05-11 08:48 UTC, tomazaw commented on views/admin/show_organisations.ejs
> +        <h3 class="col-md-8 mx-auto text-center">Przeglądaj organizacje</h1>
opened h3 closed h1

2023-05-11 09:18 UTC, macibol775 approved these changes
ok

2023-05-11 09:20 UTC, tomazaw approved these changes

2023-05-11 09:20 UTC, tomazaw commented on views/admin/show_organisations.ejs
> +                                <input type="hidden" name="_id" value="<%=organisation._id%>">
no closing /

2023-05-11 09:29 UTC, macibol775 commented on views/employer/manage_employer.ejs
> +                <div id="employerSaveResult" class="mt-2"></div>
not part of a form

2023-05-11 09:29 UTC, macibol775 commented on views/organisation/manage_organisation.ejs
> +                <div id="organisationSaveResult" class="mt-2"></div>
not part of a form

2023-05-11 09:29 UTC, macibol775 requested changes
response message not part of a form

2023-05-11 09:49 UTC, macibol775 approved these changes
okk

2023-05-11 09:53 UTC, MasterCoookie approved these changes
Check if init is needed and TODO - protect admin routes

2023-05-11 09:53 UTC, MasterCoookie commented on controllers/adminController.js
> +        const all_organisations = (await Organisation.find({})).map(org => org.toObject());
Agreed

2023-05-11 09:53 UTC, MasterCoookie commented on controllers/adminController.js
> +        await Employer.init();
Init most likely not needed

2023-05-11 09:53 UTC, MasterCoookie commented on routes/adminRoutes.js
Protect routes soon

2023-05-11 09:57 UTC, merged