Login script
MasterCoookie/szychta-pl pull request #29
Opened 2023-04-21 20:08 UTC by bartorl

2023-04-21 20:11 UTC, macibol775 commented on views/auth/login.ejs
> +            if(response.msg !== null){
can be replaced with else if(response.msg)

2023-04-21 20:12 UTC, macibol775 approved these changes
if works ok

2023-04-21 21:05 UTC, MasterCoookie requested changes
add code

2023-04-21 21:05 UTC, MasterCoookie commented on controllers/authController.js
> +                console.log("OK");
not needed log

2023-04-21 21:05 UTC, MasterCoookie commented on controllers/authController.js
> +                res.json({ msg: 'Niewłaściwe dane' });
no code

2023-04-21 21:05 UTC, MasterCoookie commented on controllers/authController.js
> +            res.json({ msg: 'Niewłaściwe dane' });
no code

2023-04-21 21:20 UTC, MasterCoookie approved these changes

2023-04-21 21:21 UTC, merged

2023-04-22 14:26 UTC, WojciechPtas reviewed
LGTM