35 handle session
MasterCoookie/szychta-pl pull request #38
Opened 2023-04-23 22:10 UTC by bartorl

Added session menagment and reading _id from session

2023-04-23 22:16 UTC, macibol775 commented on controllers/authController.js
> +                sessionController.sendAplicantInfoToSession(req, applicant.name, applicant.email, applicant._id);
aPPlicant

2023-04-23 22:17 UTC, macibol775 commented on controllers/sessionController.js
> +const sendAplicantInfoToSession = (req, name, email, _id) => {
aPPlicant

2023-04-23 22:17 UTC, macibol775 commented on controllers/sessionController.js
> +  sendAplicantInfoToSession,
aPPlicant

2023-04-23 22:18 UTC, macibol775 commented on controllers/authController.js
> +                sessionController.sendAplicantInfoToSession(req, applicant.name, applicant.email, applicant._id);
name + surname

2023-04-23 22:19 UTC, tomazaw commented on controllers/authController.js
>                  console.log("Loged in");
Log and typo inside log

2023-04-23 22:19 UTC, MasterCoookie requested changes
Rename pls

2023-04-23 22:19 UTC, MasterCoookie commented on controllers/sessionController.js
> +const sessionAuthentication = (req) => {
Name method as method

2023-04-23 22:19 UTC, MasterCoookie commented on controllers/sessionController.js
> +const sendAplicantInfoToSession = (req, name, email, _id) => {
We dont send anythong, we save/store it

2023-04-23 22:19 UTC, macibol775 requested changes
typos

2023-04-23 22:32 UTC, macibol775 approved these changes

2023-04-24 10:51 UTC, MasterCoookie approved these changes

2023-04-24 10:52 UTC, WojciechPtas approved these changes
LGTM

2023-04-24 11:04 UTC, merged