69 create and style applying component
MasterCoookie/szychta-pl pull request #74
Opened 2023-05-04 12:31 UTC by tomazaw

2023-05-04 12:38 UTC, bartorl commented on views/apply/applyingFormula.ejs
> +                    <input type="text" name="email" id="email" value="<%= applicant.email %>" />
Type email insted of text

2023-05-04 12:38 UTC, bartorl commented on views/apply/applyingFormula.ejs
> +                    <input type="text" name="phoneNumber" id="phoneNumber" value="<%= applicant.phoneNumber %>" />
Type tel

2023-05-04 12:43 UTC, MasterCoookie requested changes
change model according to comments and require login to apply

2023-05-04 12:43 UTC, MasterCoookie commented on controllers/applyController.js
> +        const application = await Application.create({ email, phoneNumber, homeAddress, jobAdvertID, applicationDate, questionAnswers, relativeSkills, applicantID, relativeDocuments });
application not used

2023-05-04 12:43 UTC, MasterCoookie commented on models/applicationModel.js
> +        type: String,
wrong type

2023-05-04 12:43 UTC, MasterCoookie commented on models/applicationModel.js
> +        type: String,
wrong type

2023-05-04 12:43 UTC, MasterCoookie commented on models/applicationModel.js
> +        type: [String],
change to key(question) value(answer) pair

2023-05-04 12:43 UTC, MasterCoookie commented on public/js/apply.js
> +    let questionsArray = Array.from(document.getElementsByClassName("question")).filter(element => element.value !== "").map(element => element.value);
change to const

2023-05-04 12:43 UTC, MasterCoookie commented on public/js/apply.js
> +    let filesArray = Array.from(document.getElementsByClassName("document")).filter(element => element.checked).map(element => element.value);
change to const

2023-05-04 16:20 UTC, macibol775 commented on controllers/applyController.js
> +        if(req.query.id == null) {
Logika ifów mogłaby być elegantsza

2023-05-04 16:26 UTC, macibol775 commented on models/applicationModel.js
> +module.exports = Application;
endl

2023-05-04 16:27 UTC, macibol775 commented on public/js/apply.js
> +    let questionsArray = Array.from(document.getElementsByClassName("question")).filter(element => element.value !== "").map(element => element.value);
x2

2023-05-04 16:29 UTC, macibol775 commented on public/uploads/6452537ac426609fbf674e71/docs/capybara-square-1.jpg.optimal.png
why so many capibaras?

2023-05-04 16:30 UTC, macibol775 commented on views/apply/applyingFormula.ejs
> +<%- include('../partials/footer.ejs') %>
endl

2023-05-04 16:33 UTC, macibol775 commented on views/apply/applyingFormula.ejs
> +        <div>
3 divy są tu otwieranie i zamykają się na końcu - bez sensu

2023-05-04 16:33 UTC, macibol775 commented on views/apply/applyingFormula.ejs
> +                    <div>Email:</div>
label instead of div

2023-05-04 16:33 UTC, macibol775 commented on views/apply/applyingFormula.ejs
> +                    <div>Email:</div>
x ileśtam

2023-05-04 20:44 UTC, tomazaw commented on views/apply/applyingFormula.ejs
> +        <div>
To jest do styli tylko nie są jeszcze nadane klasy

2023-05-04 22:10 UTC, macibol775 commented on models/applicationModel.js
> +    applicantID: {
change to applicant_id

2023-05-04 22:10 UTC, macibol775 commented on models/applicationModel.js
> +    jobAdvertID: {
change to jobAdvert_id

2023-05-04 22:13 UTC, macibol775 commented on controllers/applyController.js
> +const showApplyingFormula = async (req, res) => {
form, not formula

2023-05-04 22:13 UTC, macibol775 commented on routes/applicantRoutes.js
> +router.get('/apply', authMiddleware.require_login , applyController.showApplyingFormula);
form, not formula

2023-05-04 22:13 UTC, macibol775 commented on views/apply/applyingFormula.ejs
> +                    <label for="phone">Numer telefonu:</label>
for="phoneNumber"

2023-05-04 22:17 UTC, macibol775 commented on controllers/applyController.js
> +                res.render('apply/applyingFormula', { title: 'Apply', jobAdvert, applicant });
title po polsku

2023-05-04 22:18 UTC, macibol775 commented on views/apply/applyingFormula.ejs
> +                                <input type="text" class = "questionAnswer">
na przyszłość albo wszędzie "=" bez spacji, albo otoczone spacjami
czyli żeby było
type="text" class="questionAnswer" ALBO type = "text" class = "questionAnswer"
to jest uwaga na przyszłość

2023-05-04 22:21 UTC, macibol775 commented on views/jobOffer/show_offer_details.ejs
> +            <a href="/advert/apply/?id=<%= jobAdvert.id %>">
does it work? check

2023-05-04 22:22 UTC, macibol775 commented on views/jobOffer/show_offer_details.ejs
> +            <a href="/advert/apply/?id=<%= jobAdvert.id %>">
if not, add defect

2023-05-04 22:23 UTC, macibol775 requested changes
kilka korekt

2023-05-04 22:25 UTC, macibol775 approved these changes

2023-05-05 10:25 UTC, MasterCoookie approved these changes

2023-05-05 10:48 UTC, merged