63 create employer model
MasterCoookie/szychta-pl pull request #77
Opened 2023-05-04 18:19 UTC by bartorl

2023-05-04 18:45 UTC, macibol775 commented on controllers/authController.js
> +const Employer = require('../models/empolyerModel');
empolyer?

2023-05-04 18:47 UTC, macibol775 commented on controllers/authController.js
> +//shpuld be move to admin controller when created
I know that it is a comment, but please...

2023-05-04 18:48 UTC, macibol775 commented on controllers/authController.js
> +        console.log("New employer %s created", email, permissionLevel);
does it work properly?

2023-05-04 18:48 UTC, macibol775 commented on controllers/authController.js
> +        res.status(201).jason({ redirect: 'login '});
JASON?!?

2023-05-04 18:48 UTC, macibol775 commented on controllers/authController.js
> +        res.status(201).jason({ redirect: 'login '});
path without space

2023-05-04 18:50 UTC, macibol775 commented on controllers/employerController.js
> +const Employer = require('../models/empolyerModel');
empolyer?

2023-05-04 18:51 UTC, macibol775 commented on controllers/employerController.js
> +        res.render('employer/employerPanel', { title: 'employerPanel' });
we've decided that frontend should be in polish, so why title is in english?

2023-05-04 18:53 UTC, macibol775 commented on controllers/sessionController.js
>    authenticationAfterloggingIn,
Change L in Login to capital letter (here and above)

2023-05-04 18:54 UTC, macibol775 commented on models/empolyerModel.js
RENAME!

2023-05-04 18:55 UTC, macibol775 commented on models/empolyerModel.js
> +module.exports = Employer;
(endl)

2023-05-04 18:57 UTC, macibol775 requested changes
generally typos

2023-05-04 20:20 UTC, bartorl commented on controllers/authController.js
> +        console.log("New employer %s created", email, permissionLevel);
Yes

2023-05-04 21:19 UTC, macibol775 approved these changes

2023-05-04 21:36 UTC, MasterCoookie requested changes
Send statuses and fix typo in title

2023-05-04 21:36 UTC, MasterCoookie commented on controllers/authController.js
> +        res.json({ errors });
send status

2023-05-04 21:36 UTC, MasterCoookie commented on controllers/authController.js
> +        res.json({ errors });
send code

2023-05-04 21:36 UTC, MasterCoookie commented on controllers/authController.js
> +                    console.log("Logged in as employer");
In those kind of msg, say who logged in

2023-05-04 21:36 UTC, MasterCoookie commented on controllers/employerController.js
> +        res.render('employer/employerPanel', { title: 'panelPracownika' });
brak spacji i duża pierwsza litera

2023-05-04 21:36 UTC, MasterCoookie commented on controllers/sessionController.js
> +    req.session.employer = {  name: name, surname: surname, _id: _id, email: email, level: permLevel };
In those kind of assignment you can use shortened version. If key name matches value name u can write
`{ name, surname, _id } itd...`

2023-05-04 21:36 UTC, MasterCoookie commented on models/employerModel.js
> +    if (!this.isModified('password')){
Duplicated code, but will pass this time

2023-05-04 21:50 UTC, bartorl commented on controllers/sessionController.js
> +    req.session.employer = {  name: name, surname: surname, _id: _id, email: email, level: permLevel };
Will use it next time if possible

2023-05-05 10:21 UTC, MasterCoookie approved these changes

2023-05-05 12:20 UTC, merged